const animals = [
  "Cat",
  "Dog",
  "Elephant",
  "Tiger",
  "Lion",
  "Zebra",
  "Giraffe",
  "Panda",
  "Koala",
  "Kangaroo",
  "Penguin",
  "Dolphin",
  "Whale",
  "Shark",
  "Horse",
  "Cow",
  "Sheep",
  "Goat",
  "Pig",
  "Rabbit",
  "Squirrel",
  "Bear",
  "Wolf",
  "Fox",
  "Hedgehog",
  "Otter",
  "Moose",
  "Deer",
  "Cheetah",
  "Leopard",
  "Rhinoceros",
  "Hippopotamus",
  "Crocodile",
  "Alligator",
  "Lemur",
  "Chimpanzee",
  "Gorilla",
  "Orangutan",
  "Sloth",
  "Armadillo",
  "Antelope",
  "Peacock",
  "Owl",
  "Eagle",
  "Falcon",
  "Parrot",
  "Flamingo",
  "Octopus",
  "Jellyfish",
  "Turtle",
  "Abraham Lincoln",
  "Albert Einstein",
  "Angelina Jolie",
  "Barack Obama",
  "Beyoncé",
  "Bill Gates",
  "Bruce Springsteen",
  "Buckingham Palace",
  "Chris Hemsworth",
  "Colosseum",
  "Cristiano Ronaldo",
  "Daniel Radcliffe",
  "David Beckham",
  "Donald Trump",
  "Dwayne The Rock Johnson",
  "Eiffel Tower",
  "Elon Musk",
  "Emma Watson",
  "Elvis Presley",
  "Franklin D. Roosevelt",
  "Grand Canyon",
  "George Washington",
  "Great Wall of China",
  "Hugh Jackman",
  "Jennifer Lawrence",
  "Joe Biden",
  "John F. Kennedy",
  "Johnny Depp",
  "Justin Bieber",
  "Kim Kardashian",
  "LeBron James",
  "Lionel Messi",
  "Leonardo DiCaprio",
  "Leonardo da Vinci",
  "Louvre Museum",
  "Machu Picchu",
  "Marilyn Monroe",
  "Martin Luther King Jr.",
  "Meryl Streep",
  "Michael Jackson",
  "Michael Jordan",
  "Michael Phelps",
  "Mount Everest",
  "Mount Rushmore",
  "Muhammad Ali",
  "Notre Dame Cathedral",
  "Novak Djokovic",
  "Oprah Winfrey",
  "Queen Elizabeth",
  "Patrick Mahomes",
  "Rafael Nadal",
  "Rihanna",
  "Robert Downey Jr.",
  "Scarlett Johansson",
  "Serena Williams",
  "Simone Biles",
  "Statue of Liberty",
  "Steve Jobs",
  "Stephen Curry",
  "Sydney Opera House",
  "Taylor Swift",
  "Tiger woods",
  "Thomas Jefferson",
  "Tom Brady",
  "Tower of London",
  "Winston Churchill",
  "Vatican City"
];

export default animals;